runtime: nodejs
env: flex
resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2